#pragma once
#include <wdm.h>
#ifndef IOCTL_H
#define IOCTL_H

#ifndef CTL_CODE
#pragma message("CTL_CODE undefined. Include winioctl.h or wdm.h")
#endif

#define DEVICE_NAME_STRING			L"\\Device\\GetProcessInfo" 
#define SYMBOLIC_NAME_STRING		L"\\DosDevices\\GetProcessInfo"


#define GETGDTABLE\
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812,  METHOD_BUFFERED, FILE_ANY_ACCESS)

#define GETIDTABLE\
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81E,  METHOD_BUFFERED, FILE_ANY_ACCESS)

#define GETSYSCALL64TRACETABLE\
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81F,  METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SETSYSCALL64HOOK\
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x813,	METHOD_NEITHER, FILE_ANY_ACCESS)
#define UNSETSYSCALL64HOOK\
		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x814,	METHOD_NEITHER, FILE_ANY_ACCESS)

#endif